export enum HealthFacilityType {
  PHARMACY = 'PHARMACY',
  CLINIC = 'CLINIC',
  LABORATORY = 'LABORATORY',
  PRIMARY_HOSPITAL = 'PRIMARY_HOSPITAL',
  GENERAL_HOSPITAL = 'GENERAL_HOSPITAL',
  SPECIALIZED_HOSPITAL = 'SPECIALIZED_HOSPITAL'
}
