export enum CoverageType {
  BASIC = 'BASIC',
  STANDARD = 'STANDARD',
  PREMIUM = 'PREMIUM',
  EXECUTIVE = 'EXECUTIVE',
  
  // Coverage Categories
  INPATIENT = 'INPATIENT',
  OUTPATIENT = 'OUTPATIENT',
  DENTAL = 'DENTAL',
  OPTICAL = 'OPTICAL',
  MATERNITY = 'MATERNITY',
  EMERGENCY = 'EMERGENCY',
  CHRONIC = 'CHRONIC',
  PREVENTIVE = 'PREVENTIVE'
}
