export enum ServiceType {
  // Outpatient Services
  GENERAL_CONSULTATION = 'GENERAL_CONSULTATION',
  SPECIALIST_CONSULTATION = 'SPECIALIST_CONSULTATION',
  LABORATORY_TESTS = 'LABORATORY_TESTS',
  IMAGING = 'IMAGING',
  PRESCRIPTION_DRUGS = 'PRESCRIPTION_DRUGS',
  PHYSIOTHERAPY = 'PHYSIOTHERAPY',
  VACCINATION = 'VACCINATION',
  
  // Inpatient Services
  HOSPITALIZATION = 'HOSPITALIZATION',
  SURGERY = 'SURGERY',
  ICU_CARE = 'ICU_CARE',
  MATERNITY_CARE = 'MATERNITY_CARE',
  
  // Emergency Services
  EMERGENCY_ROOM = 'EMERGENCY_ROOM',
  AMBULANCE = 'AMBULANCE',
  
  // Specialized Services
  DENTAL_CARE = 'DENTAL_CARE',
  OPTICAL_CARE = 'OPTICAL_CARE',
  MENTAL_HEALTH = 'MENTAL_HEALTH',
  
  // Chronic Disease Management
  DIALYSIS = 'DIALYSIS',
  CANCER_TREATMENT = 'CANCER_TREATMENT',
  DIABETES_CARE = 'DIABETES_CARE',
  
  // Preventive Care
  ANNUAL_CHECKUP = 'ANNUAL_CHECKUP',
  IMMUNIZATION = 'IMMUNIZATION',
  SCREENING = 'SCREENING',
  
  // Rehabilitation
  PHYSICAL_THERAPY = 'PHYSICAL_THERAPY',
  OCCUPATIONAL_THERAPY = 'OCCUPATIONAL_THERAPY',
  SPEECH_THERAPY = 'SPEECH_THERAPY',
  
  // Medical Equipment
  MEDICAL_DEVICES = 'MEDICAL_DEVICES',
  PROSTHETICS = 'PROSTHETICS',
  
  // Other
  HOME_CARE = 'HOME_CARE',
  PALLIATIVE_CARE = 'PALLIATIVE_CARE'
}
