export enum Role {
  ADMIN = 'ADMIN',
  INSURANCE_ADMIN = 'INSURANCE_ADMIN',
  CORPORATE_ADMIN = 'CORPORATE_ADMIN',
  PROVIDER_ADMIN = 'PROVIDER_ADMIN',
  MEMBER = 'MEMBER',
  PROVIDER = 'PROVIDER',
  STAFF = 'STAFF'
}